language: php

php:
  - 8.0

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 8.0
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer self-update --1
  - travis_retry composer config --global github-oauth.github.com "$GITHUB_TOKEN"
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.4"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --no-interaction
  - travis_retry composer require php-coveralls/php-coveralls:~2.0

script:
  - vendor/bin/phpcs --standard=psr2 src -n
  - vendor/bin/phpunit --coverage-text --coverage-clover=.build/logs/clover.xml

after_success:
  - sh -c 'php vendor/bin/coveralls -v'
